#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagemenDocument
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DokumenManagement")]
	public partial class AppDbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_dokumen(tb_dokumen instance);
    partial void Updatetb_dokumen(tb_dokumen instance);
    partial void Deletetb_dokumen(tb_dokumen instance);
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    partial void Inserttb_history(tb_history instance);
    partial void Updatetb_history(tb_history instance);
    partial void Deletetb_history(tb_history instance);
    partial void Inserttb_identita(tb_identita instance);
    partial void Updatetb_identita(tb_identita instance);
    partial void Deletetb_identita(tb_identita instance);
    #endregion
		
		public AppDbContextDataContext() : 
				base(global::ManagemenDocument.Properties.Settings.Default.DokumenManagementConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AppDbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppDbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppDbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppDbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_dokumen> tb_dokumens
		{
			get
			{
				return this.GetTable<tb_dokumen>();
			}
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
		
		public System.Data.Linq.Table<tb_history> tb_histories
		{
			get
			{
				return this.GetTable<tb_history>();
			}
		}
		
		public System.Data.Linq.Table<tb_identita> tb_identitas
		{
			get
			{
				return this.GetTable<tb_identita>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_dokumen")]
	public partial class tb_dokumen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dokumen;
		
		private string _nameDokumen;
		
		private string _agendaDokumen;
		
		private string _perihalDokumen;
		
		private string _pengirimDokumen;
		
		private string _token_dokumen;
		
		private string _penerima_pertama;
		
		private int _id_pemilik;
		
		private int _id_penerima;
		
		private string _uraianDokumen;
		
		private System.DateTime _tgl_diterima;
		
		private System.DateTime _tgl_dokumen;
		
		private System.DateTime _tgl_agendaAwal;
		
		private System.DateTime _tgl_agendaAkhir;
		
		private System.DateTime _tgl_createdAt;
		
		private string _imagePath;
		
		private string _imageQrCode;
		
		private EntitySet<tb_history> _tb_histories;
		
		private EntityRef<tb_user> _tb_user;
		
		private EntityRef<tb_user> _tb_user1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dokumenChanging(int value);
    partial void Onid_dokumenChanged();
    partial void OnnameDokumenChanging(string value);
    partial void OnnameDokumenChanged();
    partial void OnagendaDokumenChanging(string value);
    partial void OnagendaDokumenChanged();
    partial void OnperihalDokumenChanging(string value);
    partial void OnperihalDokumenChanged();
    partial void OnpengirimDokumenChanging(string value);
    partial void OnpengirimDokumenChanged();
    partial void Ontoken_dokumenChanging(string value);
    partial void Ontoken_dokumenChanged();
    partial void Onpenerima_pertamaChanging(string value);
    partial void Onpenerima_pertamaChanged();
    partial void Onid_pemilikChanging(int value);
    partial void Onid_pemilikChanged();
    partial void Onid_penerimaChanging(int value);
    partial void Onid_penerimaChanged();
    partial void OnuraianDokumenChanging(string value);
    partial void OnuraianDokumenChanged();
    partial void Ontgl_diterimaChanging(System.DateTime value);
    partial void Ontgl_diterimaChanged();
    partial void Ontgl_dokumenChanging(System.DateTime value);
    partial void Ontgl_dokumenChanged();
    partial void Ontgl_agendaAwalChanging(System.DateTime value);
    partial void Ontgl_agendaAwalChanged();
    partial void Ontgl_agendaAkhirChanging(System.DateTime value);
    partial void Ontgl_agendaAkhirChanged();
    partial void Ontgl_createdAtChanging(System.DateTime value);
    partial void Ontgl_createdAtChanged();
    partial void OnimagePathChanging(string value);
    partial void OnimagePathChanged();
    partial void OnimageQrCodeChanging(string value);
    partial void OnimageQrCodeChanged();
    #endregion
		
		public tb_dokumen()
		{
			this._tb_histories = new EntitySet<tb_history>(new Action<tb_history>(this.attach_tb_histories), new Action<tb_history>(this.detach_tb_histories));
			this._tb_user = default(EntityRef<tb_user>);
			this._tb_user1 = default(EntityRef<tb_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dokumen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dokumen
		{
			get
			{
				return this._id_dokumen;
			}
			set
			{
				if ((this._id_dokumen != value))
				{
					this.Onid_dokumenChanging(value);
					this.SendPropertyChanging();
					this._id_dokumen = value;
					this.SendPropertyChanged("id_dokumen");
					this.Onid_dokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameDokumen", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nameDokumen
		{
			get
			{
				return this._nameDokumen;
			}
			set
			{
				if ((this._nameDokumen != value))
				{
					this.OnnameDokumenChanging(value);
					this.SendPropertyChanging();
					this._nameDokumen = value;
					this.SendPropertyChanged("nameDokumen");
					this.OnnameDokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agendaDokumen", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string agendaDokumen
		{
			get
			{
				return this._agendaDokumen;
			}
			set
			{
				if ((this._agendaDokumen != value))
				{
					this.OnagendaDokumenChanging(value);
					this.SendPropertyChanging();
					this._agendaDokumen = value;
					this.SendPropertyChanged("agendaDokumen");
					this.OnagendaDokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perihalDokumen", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string perihalDokumen
		{
			get
			{
				return this._perihalDokumen;
			}
			set
			{
				if ((this._perihalDokumen != value))
				{
					this.OnperihalDokumenChanging(value);
					this.SendPropertyChanging();
					this._perihalDokumen = value;
					this.SendPropertyChanged("perihalDokumen");
					this.OnperihalDokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pengirimDokumen", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pengirimDokumen
		{
			get
			{
				return this._pengirimDokumen;
			}
			set
			{
				if ((this._pengirimDokumen != value))
				{
					this.OnpengirimDokumenChanging(value);
					this.SendPropertyChanging();
					this._pengirimDokumen = value;
					this.SendPropertyChanged("pengirimDokumen");
					this.OnpengirimDokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token_dokumen", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string token_dokumen
		{
			get
			{
				return this._token_dokumen;
			}
			set
			{
				if ((this._token_dokumen != value))
				{
					this.Ontoken_dokumenChanging(value);
					this.SendPropertyChanging();
					this._token_dokumen = value;
					this.SendPropertyChanged("token_dokumen");
					this.Ontoken_dokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penerima_pertama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string penerima_pertama
		{
			get
			{
				return this._penerima_pertama;
			}
			set
			{
				if ((this._penerima_pertama != value))
				{
					this.Onpenerima_pertamaChanging(value);
					this.SendPropertyChanging();
					this._penerima_pertama = value;
					this.SendPropertyChanged("penerima_pertama");
					this.Onpenerima_pertamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pemilik", DbType="Int NOT NULL")]
		public int id_pemilik
		{
			get
			{
				return this._id_pemilik;
			}
			set
			{
				if ((this._id_pemilik != value))
				{
					if (this._tb_user1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pemilikChanging(value);
					this.SendPropertyChanging();
					this._id_pemilik = value;
					this.SendPropertyChanged("id_pemilik");
					this.Onid_pemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_penerima", DbType="Int NOT NULL")]
		public int id_penerima
		{
			get
			{
				return this._id_penerima;
			}
			set
			{
				if ((this._id_penerima != value))
				{
					if (this._tb_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_penerimaChanging(value);
					this.SendPropertyChanging();
					this._id_penerima = value;
					this.SendPropertyChanged("id_penerima");
					this.Onid_penerimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uraianDokumen", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string uraianDokumen
		{
			get
			{
				return this._uraianDokumen;
			}
			set
			{
				if ((this._uraianDokumen != value))
				{
					this.OnuraianDokumenChanging(value);
					this.SendPropertyChanging();
					this._uraianDokumen = value;
					this.SendPropertyChanged("uraianDokumen");
					this.OnuraianDokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_diterima", DbType="DateTime NOT NULL")]
		public System.DateTime tgl_diterima
		{
			get
			{
				return this._tgl_diterima;
			}
			set
			{
				if ((this._tgl_diterima != value))
				{
					this.Ontgl_diterimaChanging(value);
					this.SendPropertyChanging();
					this._tgl_diterima = value;
					this.SendPropertyChanged("tgl_diterima");
					this.Ontgl_diterimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_dokumen", DbType="DateTime NOT NULL")]
		public System.DateTime tgl_dokumen
		{
			get
			{
				return this._tgl_dokumen;
			}
			set
			{
				if ((this._tgl_dokumen != value))
				{
					this.Ontgl_dokumenChanging(value);
					this.SendPropertyChanging();
					this._tgl_dokumen = value;
					this.SendPropertyChanged("tgl_dokumen");
					this.Ontgl_dokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_agendaAwal", DbType="DateTime NOT NULL")]
		public System.DateTime tgl_agendaAwal
		{
			get
			{
				return this._tgl_agendaAwal;
			}
			set
			{
				if ((this._tgl_agendaAwal != value))
				{
					this.Ontgl_agendaAwalChanging(value);
					this.SendPropertyChanging();
					this._tgl_agendaAwal = value;
					this.SendPropertyChanged("tgl_agendaAwal");
					this.Ontgl_agendaAwalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_agendaAkhir", DbType="DateTime NOT NULL")]
		public System.DateTime tgl_agendaAkhir
		{
			get
			{
				return this._tgl_agendaAkhir;
			}
			set
			{
				if ((this._tgl_agendaAkhir != value))
				{
					this.Ontgl_agendaAkhirChanging(value);
					this.SendPropertyChanging();
					this._tgl_agendaAkhir = value;
					this.SendPropertyChanged("tgl_agendaAkhir");
					this.Ontgl_agendaAkhirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime tgl_createdAt
		{
			get
			{
				return this._tgl_createdAt;
			}
			set
			{
				if ((this._tgl_createdAt != value))
				{
					this.Ontgl_createdAtChanging(value);
					this.SendPropertyChanging();
					this._tgl_createdAt = value;
					this.SendPropertyChanged("tgl_createdAt");
					this.Ontgl_createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagePath", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string imagePath
		{
			get
			{
				return this._imagePath;
			}
			set
			{
				if ((this._imagePath != value))
				{
					this.OnimagePathChanging(value);
					this.SendPropertyChanging();
					this._imagePath = value;
					this.SendPropertyChanged("imagePath");
					this.OnimagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageQrCode", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string imageQrCode
		{
			get
			{
				return this._imageQrCode;
			}
			set
			{
				if ((this._imageQrCode != value))
				{
					this.OnimageQrCodeChanging(value);
					this.SendPropertyChanging();
					this._imageQrCode = value;
					this.SendPropertyChanged("imageQrCode");
					this.OnimageQrCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dokumen_tb_history", Storage="_tb_histories", ThisKey="id_dokumen", OtherKey="id_dokumen")]
		public EntitySet<tb_history> tb_histories
		{
			get
			{
				return this._tb_histories;
			}
			set
			{
				this._tb_histories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_dokumen", Storage="_tb_user", ThisKey="id_penerima", OtherKey="id_user", IsForeignKey=true)]
		public tb_user tb_user
		{
			get
			{
				return this._tb_user.Entity;
			}
			set
			{
				tb_user previousValue = this._tb_user.Entity;
				if (((previousValue != value) 
							|| (this._tb_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_user.Entity = null;
						previousValue.tb_dokumens.Remove(this);
					}
					this._tb_user.Entity = value;
					if ((value != null))
					{
						value.tb_dokumens.Add(this);
						this._id_penerima = value.id_user;
					}
					else
					{
						this._id_penerima = default(int);
					}
					this.SendPropertyChanged("tb_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_dokumen1", Storage="_tb_user1", ThisKey="id_pemilik", OtherKey="id_user", IsForeignKey=true)]
		public tb_user tb_user1
		{
			get
			{
				return this._tb_user1.Entity;
			}
			set
			{
				tb_user previousValue = this._tb_user1.Entity;
				if (((previousValue != value) 
							|| (this._tb_user1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_user1.Entity = null;
						previousValue.tb_dokumens1.Remove(this);
					}
					this._tb_user1.Entity = value;
					if ((value != null))
					{
						value.tb_dokumens1.Add(this);
						this._id_pemilik = value.id_user;
					}
					else
					{
						this._id_pemilik = default(int);
					}
					this.SendPropertyChanged("tb_user1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_histories(tb_history entity)
		{
			this.SendPropertyChanging();
			entity.tb_dokumen = this;
		}
		
		private void detach_tb_histories(tb_history entity)
		{
			this.SendPropertyChanging();
			entity.tb_dokumen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_user")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _name;
		
		private string _username;
		
		private string _no_identitas;
		
		private System.Nullable<int> _id_identitas;
		
		private string _alamat;
		
		private string _phoneNumber;
		
		private string _password;
		
		private int _verify;
		
		private int _level;
		
		private System.DateTime _createdAt;
		
		private EntitySet<tb_dokumen> _tb_dokumens;
		
		private EntitySet<tb_dokumen> _tb_dokumens1;
		
		private EntityRef<tb_identita> _tb_identita;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onno_identitasChanging(string value);
    partial void Onno_identitasChanged();
    partial void Onid_identitasChanging(System.Nullable<int> value);
    partial void Onid_identitasChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnverifyChanging(int value);
    partial void OnverifyChanged();
    partial void OnlevelChanging(int value);
    partial void OnlevelChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    #endregion
		
		public tb_user()
		{
			this._tb_dokumens = new EntitySet<tb_dokumen>(new Action<tb_dokumen>(this.attach_tb_dokumens), new Action<tb_dokumen>(this.detach_tb_dokumens));
			this._tb_dokumens1 = new EntitySet<tb_dokumen>(new Action<tb_dokumen>(this.attach_tb_dokumens1), new Action<tb_dokumen>(this.detach_tb_dokumens1));
			this._tb_identita = default(EntityRef<tb_identita>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_identitas", DbType="VarChar(50)")]
		public string no_identitas
		{
			get
			{
				return this._no_identitas;
			}
			set
			{
				if ((this._no_identitas != value))
				{
					this.Onno_identitasChanging(value);
					this.SendPropertyChanging();
					this._no_identitas = value;
					this.SendPropertyChanged("no_identitas");
					this.Onno_identitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_identitas", DbType="Int")]
		public System.Nullable<int> id_identitas
		{
			get
			{
				return this._id_identitas;
			}
			set
			{
				if ((this._id_identitas != value))
				{
					if (this._tb_identita.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_identitasChanging(value);
					this.SendPropertyChanging();
					this._id_identitas = value;
					this.SendPropertyChanged("id_identitas");
					this.Onid_identitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(50)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="VarChar(50)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verify", DbType="Int NOT NULL")]
		public int verify
		{
			get
			{
				return this._verify;
			}
			set
			{
				if ((this._verify != value))
				{
					this.OnverifyChanging(value);
					this.SendPropertyChanging();
					this._verify = value;
					this.SendPropertyChanged("verify");
					this.OnverifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int NOT NULL")]
		public int level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this.OnlevelChanging(value);
					this.SendPropertyChanging();
					this._level = value;
					this.SendPropertyChanged("level");
					this.OnlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_dokumen", Storage="_tb_dokumens", ThisKey="id_user", OtherKey="id_penerima")]
		public EntitySet<tb_dokumen> tb_dokumens
		{
			get
			{
				return this._tb_dokumens;
			}
			set
			{
				this._tb_dokumens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_dokumen1", Storage="_tb_dokumens1", ThisKey="id_user", OtherKey="id_pemilik")]
		public EntitySet<tb_dokumen> tb_dokumens1
		{
			get
			{
				return this._tb_dokumens1;
			}
			set
			{
				this._tb_dokumens1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_identita_tb_user", Storage="_tb_identita", ThisKey="id_identitas", OtherKey="id_identitas", IsForeignKey=true)]
		public tb_identita tb_identita
		{
			get
			{
				return this._tb_identita.Entity;
			}
			set
			{
				tb_identita previousValue = this._tb_identita.Entity;
				if (((previousValue != value) 
							|| (this._tb_identita.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_identita.Entity = null;
						previousValue.tb_users.Remove(this);
					}
					this._tb_identita.Entity = value;
					if ((value != null))
					{
						value.tb_users.Add(this);
						this._id_identitas = value.id_identitas;
					}
					else
					{
						this._id_identitas = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_identita");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_dokumens(tb_dokumen entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = this;
		}
		
		private void detach_tb_dokumens(tb_dokumen entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = null;
		}
		
		private void attach_tb_dokumens1(tb_dokumen entity)
		{
			this.SendPropertyChanging();
			entity.tb_user1 = this;
		}
		
		private void detach_tb_dokumens1(tb_dokumen entity)
		{
			this.SendPropertyChanging();
			entity.tb_user1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_history")]
	public partial class tb_history : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_history;
		
		private int _id_user;
		
		private int _id_dokumen;
		
		private System.DateTime _createdAt;
		
		private EntityRef<tb_dokumen> _tb_dokumen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_historyChanging(int value);
    partial void Onid_historyChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onid_dokumenChanging(int value);
    partial void Onid_dokumenChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    #endregion
		
		public tb_history()
		{
			this._tb_dokumen = default(EntityRef<tb_dokumen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_history", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_history
		{
			get
			{
				return this._id_history;
			}
			set
			{
				if ((this._id_history != value))
				{
					this.Onid_historyChanging(value);
					this.SendPropertyChanging();
					this._id_history = value;
					this.SendPropertyChanged("id_history");
					this.Onid_historyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dokumen", DbType="Int NOT NULL")]
		public int id_dokumen
		{
			get
			{
				return this._id_dokumen;
			}
			set
			{
				if ((this._id_dokumen != value))
				{
					if (this._tb_dokumen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dokumenChanging(value);
					this.SendPropertyChanging();
					this._id_dokumen = value;
					this.SendPropertyChanged("id_dokumen");
					this.Onid_dokumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dokumen_tb_history", Storage="_tb_dokumen", ThisKey="id_dokumen", OtherKey="id_dokumen", IsForeignKey=true)]
		public tb_dokumen tb_dokumen
		{
			get
			{
				return this._tb_dokumen.Entity;
			}
			set
			{
				tb_dokumen previousValue = this._tb_dokumen.Entity;
				if (((previousValue != value) 
							|| (this._tb_dokumen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_dokumen.Entity = null;
						previousValue.tb_histories.Remove(this);
					}
					this._tb_dokumen.Entity = value;
					if ((value != null))
					{
						value.tb_histories.Add(this);
						this._id_dokumen = value.id_dokumen;
					}
					else
					{
						this._id_dokumen = default(int);
					}
					this.SendPropertyChanged("tb_dokumen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_identitas")]
	public partial class tb_identita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_identitas;
		
		private string _nameIdentitas;
		
		private EntitySet<tb_user> _tb_users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_identitasChanging(int value);
    partial void Onid_identitasChanged();
    partial void OnnameIdentitasChanging(string value);
    partial void OnnameIdentitasChanged();
    #endregion
		
		public tb_identita()
		{
			this._tb_users = new EntitySet<tb_user>(new Action<tb_user>(this.attach_tb_users), new Action<tb_user>(this.detach_tb_users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_identitas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_identitas
		{
			get
			{
				return this._id_identitas;
			}
			set
			{
				if ((this._id_identitas != value))
				{
					this.Onid_identitasChanging(value);
					this.SendPropertyChanging();
					this._id_identitas = value;
					this.SendPropertyChanged("id_identitas");
					this.Onid_identitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameIdentitas", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nameIdentitas
		{
			get
			{
				return this._nameIdentitas;
			}
			set
			{
				if ((this._nameIdentitas != value))
				{
					this.OnnameIdentitasChanging(value);
					this.SendPropertyChanging();
					this._nameIdentitas = value;
					this.SendPropertyChanged("nameIdentitas");
					this.OnnameIdentitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_identita_tb_user", Storage="_tb_users", ThisKey="id_identitas", OtherKey="id_identitas")]
		public EntitySet<tb_user> tb_users
		{
			get
			{
				return this._tb_users;
			}
			set
			{
				this._tb_users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_users(tb_user entity)
		{
			this.SendPropertyChanging();
			entity.tb_identita = this;
		}
		
		private void detach_tb_users(tb_user entity)
		{
			this.SendPropertyChanging();
			entity.tb_identita = null;
		}
	}
}
#pragma warning restore 1591
