<?xml version="1.0" encoding="utf-8"?><Database Name="Db_DockumenManagement" Class="AppDbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8UJEI4N\MSSQLSERVER01;Initial Catalog=Db_DockumenManagement;Integrated Security=True" SettingsObjectName="ManagemenDocument.Properties.Settings" SettingsPropertyName="Db_DockumenManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_dokumen" Member="tb_dokumens">
    <Type Name="tb_dokumen">
      <Column Name="id_dokumen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameDokumen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pengirimDokumen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_pemilik" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pemilikDokumen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_penerima" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="penerimaDokumen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uraianDokumen" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="tgl_diterima" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tgl_dokumen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tgl_agendaAwal" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tgl_agendaAkhir" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tgl_createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tb_dokumen_tb_penerima" Member="tb_penerimas" ThisKey="id_dokumen" OtherKey="id_dokumen" Type="tb_penerima" />
      <Association Name="tb_user_tb_dokumen" Member="tb_user" ThisKey="id_pemilik" OtherKey="id_user" Type="tb_user" IsForeignKey="true" />
      <Association Name="tb_user_tb_dokumen1" Member="tb_user1" ThisKey="id_penerima" OtherKey="id_user" Type="tb_user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_user" Member="tb_users">
    <Type Name="tb_user">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="no_identitas" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_identitas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="alamat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="verify" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tb_user_tb_dokumen" Member="tb_dokumens" ThisKey="id_user" OtherKey="id_pemilik" Type="tb_dokumen" />
      <Association Name="tb_user_tb_dokumen1" Member="tb_dokumens1" ThisKey="id_user" OtherKey="id_penerima" Type="tb_dokumen" />
      <Association Name="tb_user_tb_penerima" Member="tb_penerimas" ThisKey="id_user" OtherKey="id_user" Type="tb_penerima" />
      <Association Name="tb_identita_tb_user" Member="tb_identita" ThisKey="id_identitas" OtherKey="id_identitas" Type="tb_identita" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_identitas" Member="tb_identitas">
    <Type Name="tb_identita">
      <Column Name="id_identitas" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameIdentitas" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tb_identita_tb_user" Member="tb_users" ThisKey="id_identitas" OtherKey="id_identitas" Type="tb_user" />
    </Type>
  </Table>
  <Table Name="dbo.tb_penerima" Member="tb_penerimas">
    <Type Name="tb_penerima">
      <Column Name="id_penerima" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_dokumen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="namaPenerima" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tb_user_tb_penerima" Member="tb_user" ThisKey="id_user" OtherKey="id_user" Type="tb_user" IsForeignKey="true" />
      <Association Name="tb_dokumen_tb_penerima" Member="tb_dokumen" ThisKey="id_dokumen" OtherKey="id_dokumen" Type="tb_dokumen" IsForeignKey="true" />
    </Type>
  </Table>
</Database>